In [ ]:
##Netflix Movie Recommender KNN Implementation
#Author = {"PARMEET SINGH AHLUWALIA(pahluwal)", "VIJAY HAREESH(vavula)"}

In [1]:
import pandas as pd
import numpy as np

In [2]:
#neighbors = pd.read_csv('/Users/Parth/Desktop/knn.csv', sep = ',')
neighbors_with_distane = pd.read_csv('knn_withDistance.csv', sep = ',')

In [3]:
neighbors_with_distane
#sample['NeighborID']

       MovieID  NeighborID  Distance
0         8192        6294  4.542193
1         8192       12156  4.629102
2         8192        4773  4.694485
3         8192        5765  4.711531
4         8192       10462  4.723366
5        16384       14526  8.815481
6        16384        1635  8.843046
7        16384       12156  8.845963
8        16384       15530  8.849711
9        16384       13610  8.849980
10       16386       12156  3.817723
11       16386       13764  3.873437
12       16386       15303  3.906821
13       16386       11765  3.941955
14       16386        3121  3.953930
15       16389       10341  5.739963
16       16389       13328  5.819662
17       16389       17273  5.822093
18       16389       14526  5.825486
19       16389       10977  5.863769
20       16390       12156  3.553922
21       16390        3170  3.632698
22       16390       10462  3.690581
23       16390       10341  3.770010
24       16390       15303  3.775602
25        8199       15936  5.929816
26        8199        8949  5.970071
27        8199       17344  5.983167
28        8199       12258  6.000614
29        8199       10986  6.017703
...        ...         ...       ...
25727    16365        6897  4.508048
25728    16365        3957  4.551787
25729    16365       14309  4.583307
25730    16366        3170  4.332978
25731    16366       10632  4.362951
25732    16366        3937  4.402980
25733    16366       12156  4.427730
25734    16366       14604  4.431929
25735    12285        4773  6.950234
25736    12285         170  6.983904
25737    12285        3121  6.999821
25738    12285       15153  7.006038
25739    12285        9068  7.038857
25740     8178       10341  5.401031
25741     8178       12714  5.526575
25742     8178        6592  5.545809
25743     8178       12156  5.570845
25744     8178       17273  5.574468
25745    16371       10977  3.295879
25746    16371        5384  3.304708
25747    16371       12156  3.310473
25748    16371        3937  3.312963
25749    16371        3170  3.314563
25750     8180        4773  5.768393
25751     8180        7813  5.837479
25752     8180       15593  5.858572
25753     8180        9068  5.867576
25754     8180         608  5.869084
25755     8181        8949  7.376692
25756     8181       16130  7.442352

[25757 rows x 3 columns]

In [4]:
df_user_rating = pd.read_csv('Final_UserMovieRating_Filtered.csv', sep = ',', header=None)
df_user_rating.columns=['UserID','MovieID','user_rating']
#df_user_rating_sample = pd.DataFrame(columns=['UserID','MovieID','user_rating'])
#for i in df_user_rating.UserID.unique()[:100]:
    #count = count
    #df_user_rating_sam = df_user_rating[df_user_rating.UserID==i]
    #df_user_rating_sample = df_user_rating_sample.append(df_user_rating[df_user_rating.UserID==i])
#cond = (df_user_rating.UserID==2097947) | (df_user_rating.UserID==2097991) | (df_user_rating.UserID==1050083) | (df_user_rating.UserID==2097392) | (df_user_rating.UserID==302) | (df_user_rating.UserID==1049829)

In [5]:
cond = (df_user_rating.UserID==273292) | (df_user_rating.UserID==1945809) | (df_user_rating.UserID==1794216) | (df_user_rating.UserID==1863853) | (df_user_rating.UserID==2630287)
df_user_rating_sample = df_user_rating.loc[cond]

In [6]:
df_user_rating_sample

           UserID  MovieID  user_rating
0          273292     8192            4
1         1945809     8192            1
2         1794216     8192            5
3         1863853     8192            4
4         2630287     8192            1
4787      1945809    16384            4
4801      1794216    16384            4
4928       273292    16384            3
5013      2630287    16384            4
145265    1945809    16390            2
145347     273292    16390            3
208979    1945809     8199            2
216913    1945809    16401            4
222754    1945809     8219            4
235705    1794216       30            5
235769     273292       30            3
235788    2630287       30            4
353675    1945809    12293            5
353945    2630287    12293            2
353967    1794216    12293            4
354130     273292    12293            5
465136    1945809    16425            3
472400    1945809    15385            3
494348    1945809     8246            4
502534    1945809       55            3
515436    1945809     8254            1
522053    1945809     8259            3
522066    2630287     8259            3
530847    1945809    16452            2
531018    2630287    16452            3
...           ...      ...          ...
59900084  1794216    16339            4
59900173  2630287    16339            4
59981452  1863853    16343            3
59981493   273292    16343            4
59981668  1945809    16343            3
59981676  1794216    16343            5
60048619  1863853    15820            2
60057994  1945809     8158            1
60059593  1945809     8159            3
60059728   273292     8159            4
60117375  1945809     8162            3
60120102  1794216    16357            2
60120124  1863853    16357            3
60164913  1863853    16359            2
60176688   273292     8171            3
60196693  1945809     8172            4
60206884  1945809    16366            1
60219798  1945809     8178            3
60219801  1794216     8178            2
60231144  1794216     8181            4
60231188   273292     8181            3
60231321  2630287     8181            3
60314052  1863853    10921            3
60314128  2630287    10921            2
60314208  1794216    10921            2
60364405  1945809    16377            4
60364481  1863853    16377            5
60364615   273292    16377            5
60364746  2630287    16377            5
60546101  2630287    16379            2

[3502 rows x 3 columns]

In [7]:
#df_user_rating_sample
len(df_user_rating_sample.UserID.unique())

5

In [8]:
def getRecommendations(group):
    recommendations_movies = []
    #print "###########"
    workingset = group.sort('user_rating', ascending=False).head(3)
    #print workingset
    for row in workingset.itertuples():
        #intermediate = neighbors_with_distane[neighbors_with_distane.MovieID==row.MovieID]
        #print intermediate
        #print str(intermediate.NeighborID)
        recommendations_movies.append(neighbors_with_distane[['NeighborID','Distance']][neighbors_with_distane.MovieID==row.MovieID])
    recommendations_movies = pd.concat(recommendations_movies,ignore_index=True)
    return recommendations_movies

In [9]:
temp_new = df_user_rating_sample.groupby('UserID').apply(getRecommendations)
#temp_new

/Library/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:4: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

In [10]:
final_df = temp_new.reset_index(0).drop_duplicates().sort(['UserID','Distance'],ascending=True)

/Library/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

In [9]:
final_df.UserID.astype(int)
final_df#[final_df['UserID']!=final_df['NeighborID']]

       UserID  NeighborID  Distance
5     24344.0        3121  3.531371
6     24344.0        3170  3.572076
7     24344.0       12156  3.643114
8     24344.0        7593  3.726694
9     24344.0        2988  3.739806
0     24344.0       12156  3.872774
1     24344.0       10462  3.914632
2     24344.0        8776  3.932590
3     24344.0        9485  4.009527
4     24344.0        5937  4.060395
10    24344.0        8949  5.465752
11    24344.0       12156  5.506473
12    24344.0        5384  5.537968
13    24344.0        1318  5.615378
14    24344.0        3897  5.639997
0     39435.0        3937  4.265209
1     39435.0        6294  4.366909
2     39435.0        9068  4.382008
3     39435.0       17077  4.420315
4     39435.0        4285  4.420315
10    39435.0        3245  7.805864
11    39435.0        5698  7.828104
12    39435.0       13610  7.833671
13    39435.0        5407  7.846044
14    39435.0         170  7.849359
5     39435.0       10370  8.210471
6     39435.0        8343  8.222421
7     39435.0        3165  8.325740
8     39435.0       15199  8.329515
9     39435.0       12201  8.353091
..        ...         ...       ...
0   2621268.0       11678  0.000000
10  2621268.0       17381  0.000000
11  2621268.0        9703  5.667980
12  2621268.0       16425  5.831152
13  2621268.0       10632  6.050161
14  2621268.0        9061  6.083510
5   2621268.0        4080  6.382123
6   2621268.0       16201  6.410023
7   2621268.0        2937  6.571712
8   2621268.0        3901  6.617569
9   2621268.0       14526  6.668258
1   2621268.0       12156  7.604445
2   2621268.0        5583  7.608420
3   2621268.0       10462  7.610412
4   2621268.0       15045  7.620734
5   2630287.0        8392  0.000000
10  2630287.0       12156  3.543093
11  2630287.0       14526  3.683263
12  2630287.0        6294  3.698293
13  2630287.0       15045  3.739431
14  2630287.0       17533  3.762081
6   2630287.0       11765  6.694931
7   2630287.0       14915  6.727685
8   2630287.0        6897  6.745340
9   2630287.0        2988  6.760456
0   2630287.0       11432  6.810499
1   2630287.0       12791  6.850673
2   2630287.0        9059  6.871458
3   2630287.0        4297  6.873937
4   2630287.0       14604  6.896577

[1500 rows x 3 columns]

In [12]:
#final_df.to_csv('/Users/Parth/Desktop/KNN_OUTPUT.csv')